from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

class ResumeBase(BaseModel):
    filename: str = Field(..., description="Original filename of the resume.")

class ResumeCreate(ResumeBase):
    # For now, no additional fields beyond filename for creation,
    # as parsed_text will be generated by the backend.
    pass

class ResumeResponse(ResumeBase):
    id: int = Field(..., description="Unique ID of the resume.")
    parsed_text: str = Field(..., description="The full parsed text of the resume.")
    upload_date: datetime = Field(..., description="Timestamp of when the resume was uploaded.")
    # You might want to omit parsed_text for large documents in a response model
    # or create a separate endpoint for retrieving raw text. For this guide, we include it.

    class Config:
        from_attributes = True # Changed from orm_mode = True